'use client';

// ============================================================
// Intelligence Alerts Management Page
// Real database alerts generated by scoring & rule engine
// ============================================================
import React, { useState, useEffect, useCallback } from 'react';
import { useSearchParams } from 'next/navigation';
import { useAuth } from '@/components/auth/auth-provider';
import { IntelligenceNav } from '@/components/intelligence/intelligence-nav';
import { AlertCard } from '@/components/intelligence/alert-card';
import { EmptyState } from '@/components/intelligence/empty-state';
import type { IntelligenceAlert, AlertPriority, AlertStatus } from '@/types';

export default function IntelligenceAlertsPage() {
  const { getToken } = useAuth();
  const searchParams = useSearchParams();
  const projectId = searchParams.get('projectId') || '';

  const [alerts, setAlerts] = useState<IntelligenceAlert[]>([]);
  const [loading, setLoading] = useState(true);
  const [priorityFilter, setPriorityFilter] = useState<AlertPriority | ''>('');
  const [statusFilter, setStatusFilter] = useState<AlertStatus | 'all'>('unread');

  const fetchAlerts = useCallback(async () => {
    try {
      setLoading(true);
      const token = await getToken();
      if (!token) return;

      const params = new URLSearchParams();
      if (projectId) params.set('projectId', projectId);
      if (priorityFilter) params.set('priority', priorityFilter);
      if (statusFilter !== 'all') params.set('status', statusFilter);

      const res = await fetch(`/api/intelligence/alerts?${params.toString()}`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = await res.json();
      if (data.success) {
        setAlerts(data.alerts || []);
      }
    } catch {
      // silent
    } finally {
      setLoading(false);
    }
  }, [getToken, projectId, priorityFilter, statusFilter]);

  useEffect(() => {
    fetchAlerts();
  }, [fetchAlerts]);

  const handleMarkStatus = async (alertId: string, status: AlertStatus) => {
    try {
      const token = await getToken();
      if (!token) return;

      await fetch('/api/intelligence/alerts', {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ alertId, status }),
      });
      fetchAlerts();
    } catch {
      // silent
    }
  };

  return (
    <div className="intel-page-container">
      <IntelligenceNav onRefresh={fetchAlerts} />

      <div className="intel-subpage-header">
        <div>
          <h2 className="intel-subpage-title">Intelligence Alerts &amp; Notifications</h2>
          <p className="intel-subpage-desc">
            Rule-based threshold notifications for high-impact research, new patents, and competitor updates.
          </p>
        </div>
      </div>

      {/* Filter Tabs & Selectors */}
      <div className="intel-filters-toolbar">
        <div className="intel-filter-tabs">
          <button
            onClick={() => setStatusFilter('unread')}
            className={`intel-filter-pill ${statusFilter === 'unread' ? 'intel-pill-active' : ''}`}
            type="button"
          >
            Unread
          </button>
          <button
            onClick={() => setStatusFilter('read')}
            className={`intel-filter-pill ${statusFilter === 'read' ? 'intel-pill-active' : ''}`}
            type="button"
          >
            Read
          </button>
          <button
            onClick={() => setStatusFilter('archived')}
            className={`intel-filter-pill ${statusFilter === 'archived' ? 'intel-pill-active' : ''}`}
            type="button"
          >
            Archived
          </button>
          <button
            onClick={() => setStatusFilter('all')}
            className={`intel-filter-pill ${statusFilter === 'all' ? 'intel-pill-active' : ''}`}
            type="button"
          >
            All Alerts
          </button>
        </div>

        <div className="intel-filter-dropdowns">
          <select
            value={priorityFilter}
            onChange={(e) => setPriorityFilter(e.target.value as AlertPriority | '')}
            className="intel-filter-select"
          >
            <option value="">All Priorities</option>
            <option value="critical">Critical Priority Only</option>
            <option value="high">High Priority &amp; Above</option>
            <option value="medium">Medium Priority</option>
            <option value="low">Low Priority</option>
          </select>
        </div>
      </div>

      {/* Alerts Feed */}
      {loading ? (
        <div className="intel-loading-container">
          <div className="app-loading-spinner" />
          <p>Loading alerts from database...</p>
        </div>
      ) : alerts.length === 0 ? (
        <EmptyState
          title="No alerts found"
          description={
            statusFilter === 'unread'
              ? 'You have zero unread alerts. High priority findings will appear here automatically.'
              : 'No alerts match your current filter.'
          }
          actionText=""
        />
      ) : (
        <div className="intel-alerts-stack">
          {alerts.map((alert) => (
            <AlertCard
              key={alert.id}
              alert={alert}
              onMarkStatus={handleMarkStatus}
            />
          ))}
        </div>
      )}
    </div>
  );
}
